In [7]:
import numpy 

In [8]:
import numpy as np


In [9]:
a = np.array(
    []
)
a

array([], dtype=float64)

In [10]:
b = np.array([3, 4, 5, 6, 7])
b

array([3, 4, 5, 6, 7])

In [11]:
len(b)

5

In [12]:
b[0]

3

In [13]:
b.dtype

dtype('int32')

In [14]:
a.ndim

1

In [15]:
c = np.array([[2,3,4],[4,5,6],[3,6,7]])
c

array([[2, 3, 4],
       [4, 5, 6],
       [3, 6, 7]])

In [16]:
c.ndim

2

In [17]:
d = np.array([[[1,2,3], [3,4,5]], [[6,7,8],[7,8,9]]])
d

array([[[1, 2, 3],
        [3, 4, 5]],

       [[6, 7, 8],
        [7, 8, 9]]])

In [18]:
d.shape

(2, 2, 3)

In [19]:
d.ndim

3

In [20]:
c.sum(axis=1)

array([ 9, 15, 16])

In [21]:
c

array([[2, 3, 4],
       [4, 5, 6],
       [3, 6, 7]])

In [22]:
c[0:2, -1]

array([4, 6])

In [23]:
c[0:2, -1:]

array([[4],
       [6]])

In [24]:
c[0:2, -2:]

array([[3, 4],
       [5, 6]])

In [25]:
#day8
import numpy as np

In [26]:
e = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [27]:
e.ndim
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
e[:, 1] = [40, 50 , 60]
e[:3 , 1:]

array([[40,  3],
       [50,  6],
       [60,  9]])

In [29]:
e[:2 , 1:] = [[45, 46], [55, 56]]
e

array([[ 1, 45, 46],
       [ 4, 55, 56],
       [ 7, 60,  9]])

numpy.ndarray

In [30]:
e[ : , -1:]

array([[46],
       [56],
       [ 9]])

In [31]:
np.append(e, [[91], [92], [93]], axis=1)

array([[ 1, 45, 46, 91],
       [ 4, 55, 56, 92],
       [ 7, 60,  9, 93]])

In [32]:
np.delete(e, 1, axis=0)

array([[ 1, 45, 46],
       [ 7, 60,  9]])

In [33]:
e.reshape(9, 1)

array([[ 1],
       [45],
       [46],
       [ 4],
       [55],
       [56],
       [ 7],
       [60],
       [ 9]])

In [34]:
e.dtype

dtype('int32')

In [35]:
e1 = np.array([3.5, 3, 7])
e1

array([3.5, 3. , 7. ])

In [36]:
e1.astype("int64")

array([3, 3, 7], dtype=int64)

In [37]:
e1

array([3.5, 3. , 7. ])

In [38]:
f = np.array([[[4, 41], [8, 81], [7, 71]], [[3, 31], [1, 11], [5, 51]], 
              [[6, 61], [9, 91], [13, 131]]])

In [39]:
f.std(axis=0)

array([[ 1.24721913, 12.47219129],
       [ 3.55902608, 35.59026084],
       [ 3.39934634, 33.99346342]])

In [40]:
f.shape

(3, 3, 2)

In [41]:
f

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [42]:
f[0, 0, 0]

4

In [43]:
f[0, 0, :]

array([ 4, 41])

In [44]:
f[1: , 1, 1:]

array([[11],
       [91]])

In [45]:
f[1: , 1: , 0]

array([[ 1,  5],
       [ 9, 13]])

In [46]:
f[1:2 , 1: , :]

array([[[ 1, 11],
        [ 5, 51]]])

In [47]:
f[1: , 0, :]

array([[ 3, 31],
       [ 6, 61]])

In [48]:
f+1

array([[[  5,  42],
        [  9,  82],
        [  8,  72]],

       [[  4,  32],
        [  2,  12],
        [  6,  52]],

       [[  7,  62],
        [ 10,  92],
        [ 14, 132]]])

In [49]:
f-1

array([[[  3,  40],
        [  7,  80],
        [  6,  70]],

       [[  2,  30],
        [  0,  10],
        [  4,  50]],

       [[  5,  60],
        [  8,  90],
        [ 12, 130]]])

In [50]:
f

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [51]:
#Nutshell
## We create arrays
#1. np.array()
#2. np.ones() 
#3. np.zeros() 
#4. np.arange()
#5. np.linespace()
#6. np.random.randint()
## Arrays have some attributes and functions   

In [52]:
import numpy as np

In [53]:
np.linspace(1, 10, 10, dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
np.zeros((2,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [61]:
np.random.seed(54)
np.random.randint(1,6,[4,3])

array([[3, 2, 1],
       [1, 2, 2],
       [2, 5, 5],
       [5, 5, 1]])

In [62]:
np.random.rand(3, 4)
#elements are less than 1 and > 0, takes shape  

array([[0.22207173, 0.90899641, 0.73844901, 0.36877818],
       [0.95241023, 0.17536069, 0.005698  , 0.69562386],
       [0.59485159, 0.69003496, 0.66234766, 0.55941208]])

In [64]:
r = np.loadtxt("sample.txt", dtype=str)
r

array(['this', 'is', 'a', 'file', 'for', 'testing.'], dtype='<U8')

In [66]:
r = np.loadtxt("intarray.txt", dtype=int)
r

array([[12, 16, 17, 18],
       [11, 44, 66, 84],
       [23, 45, 67, 89]])

In [68]:
p = np.random.rand(3, 4)
np.savetxt("new.txt", p, delimiter="\n")